import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { TodotxtGeneratedModule, TodotxtGeneratedSharedModule } from './generated/module.js';
import { TodotxtValidator, registerValidationChecks } from './todotxt-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TodotxtAddedServices = {
    validation: {
        TodotxtValidator: TodotxtValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TodotxtServices = LangiumServices & TodotxtAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TodotxtModule: Module<TodotxtServices, PartialLangiumServices & TodotxtAddedServices> = {
    validation: {
        TodotxtValidator: () => new TodotxtValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTodotxtServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Todotxt: TodotxtServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        TodotxtGeneratedSharedModule
    );
    const Todotxt = inject(
        createDefaultModule({ shared }),
        TodotxtGeneratedModule,
        TodotxtModule
    );
    shared.ServiceRegistry.register(Todotxt);
    registerValidationChecks(Todotxt);
    return { shared, Todotxt };
}
